single consul (master) instance per host instead of additional client agent per pod to save memory/overhead. script to configure consul. consul KV watch script for changed http/ entries (->toggles nginx vhost config generation) and event watch script that invokes consul configuration reload

diff --git a/config/opt/bin/configure-consul b/config/opt/bin/configure-consul
--- a/config/opt/bin/configure-consul
+++ b/config/opt/bin/configure-consul
@@ -1,35 +1,41 @@
 #!/bin/sh
 
-[ $# -eq 3 ] || (echo "Usage: $0 MASTERHOST DATACENTER CLIENTDESTFILE" >&2; false) || exit 1
+[ $# -eq 3 ] && [ "$1" ] && [ "$2" ] && [ "$3" ] || (echo "Usage: $0 CONSULHOST DATACENTER CONFDIR" >&2; false) || exit 1
 [ "$POD_NAME" ] || (echo "Missing env var: POD_NAME" >&2; false) || exit 1
-[ "$EFFECTIVE_JSON" ] || (echo "Missing env var: POD_JSON" >&2; false) || exit 1
+[ "$EFFECTIVE_JSON" ] || (echo "Missing env var: EFFECTIVE_JSON" >&2; false) || exit 1
+[ "$POD_IP" ] || (echo "Missing env var: POD_IP" >&2; false) || exit 1
+
+CONSUL_HOST="$1"
+CONSUL_DATACENTER="$2"
+DEST_FILE="$3/pod-${POD_NAME}.json"
 
 waitForConsulMaster() {
 	for SEC in 1 1 3 3 5 10; do
-		curl -XGET "http://$CONSUL_MASTER_HOST:8500/v1/kv/?dc=$CONSUL_DATACENTER&keys" >/dev/null 2>/dev/null && return 0
+		curl -XGET "http://$CONSUL_HOST:8500/v1/kv/?dc=$CONSUL_DATACENTER&keys" >/dev/null 2>/dev/null && return 0
 		sleep $SEC
 	done
-	echo "Consul master ($CONSUL_MASTER_HOST) unavailable" >&2
+	echo "Consul master ($CONSUL_HOST) unavailable" >&2
 	return 1
 }
 
+# TODO: Write config into consul master so that no consul client required (Problem: service address must be known)
 consulConfigJq() {
 	POD_NAME_JSON="$(echo "$POD_NAME" | jq -R .)"
 	CONSUL_DATACENTER_JSON="$(echo "$CONSUL_DATACENTER" | jq -R .)"
+	#"datacenter": $CONSUL_DATACENTER_JSON,
+	#"log_level": "INFO",
+	#"node_name": $POD_NAME_JSON,
+	#"server": false,
 	cat <<-EOF
 		$EFFECTIVE_JSON | {
-			"datacenter": $CONSUL_DATACENTER_JSON,
-			"log_level": "INFO",
-			"node_name": $POD_NAME_JSON,
-			"server": false,
 			"services": [.images as \$i | .pod.services | to_entries[] as \$e | \$i[\$e.value.image]?.app?.ports[]? | {
 					"name": (\$e.key),
 					"tags": [.name],
-					"address": "",
+					"address": "$POD_IP",
 					"port": .port,
 					"enableTagOverride": false,
 					"checks": [{
-						"script": ("/usr/bin/nc -zvw1" + (if (.protocol == "udp") then "u" else "" end) + " 127.0.0.1 " + (.port|tostring)),
+						"script": ("/usr/bin/nc -zvw1" + (if (.protocol == "udp") then "u" else "" end) + " $POD_IP " + (.port|tostring)),
 						"interval": "10s"
 					}]
 				}
@@ -49,14 +55,14 @@ registerHttpHostConsulKvEntries() {
 		SERVICE_PORT="$(jq -nr "$HTTP_HOST_JSON | .port | select(. != null)")" &&
 		SERVICE_ADDRESS="$SERVICE_HOST:$SERVICE_PORT" &&
 		([ "$SERVICE_PORT" ] || (echo "Service HTTP_PORT undefined for HTTP_HOST: $HTTP_HOST" >&2; false)) &&
-		REGISTERED_SERVICE_ADDRESS="$(curl -XGET "http://$CONSUL_MASTER_HOST:8500/v1/kv/http/$HTTP_HOST?dc=$CONSUL_DATACENTER&raw" -m 10 2>/dev/null || true)" &&
+		REGISTERED_SERVICE_ADDRESS="$(curl -XGET "http://$CONSUL_HOST:8500/v1/kv/http/$HTTP_HOST?dc=$CONSUL_DATACENTER&raw" -m 3 2>/dev/null || true)" &&
 		# Disallow HTTP host override
 		([ ! "$REGISTERED_SERVICE_ADDRESS" ] || [ "$(echo "$REGISTERED_SERVICE_ADDRESS" | grep -Eo "^.{$SERVICE_HOST_LENGTH}")" = "${SERVICE_HOST}:" ] \
 			|| (echo "HTTP_HOST $HTTP_HOST is already registered for $REGISTERED_SERVICE_ADDRESS!" >&2; false)) || return 1
 		# Register pod as HTTP host
 		if [ ! "$REGISTERED_SERVICE_ADDRESS" = "${SERVICE_ADDRESS}" ]; then
 			echo "Registering proxy host $HTTP_HOST -> $SERVICE_ADDRESS"
-			[ "$(curl -XPUT "http://$CONSUL_MASTER_HOST:8500/v1/kv/http/$HTTP_HOST?dc=$CONSUL_DATACENTER" -m 10 -d "$SERVICE_ADDRESS" 2>/dev/null)" = true ] \
+			[ "$(curl -XPUT "http://$CONSUL_HOST:8500/v1/kv/http/$HTTP_HOST?dc=$CONSUL_DATACENTER" -m 3 -d "$SERVICE_ADDRESS" 2>/dev/null)" = true ] \
 				|| (echo "Failed to register HTTP_HOST in consul: $HTTP_HOST=$SERVICE_ADDRESS" >&2; false) || return 1
 		fi
 	done
@@ -72,12 +78,15 @@ httpHostEntriesJq() {
 	EOF
 }
 
-CONSUL_MASTER_HOST="$1"
-CONSUL_DATACENTER="$2"
-DEST_FILE="$3"
-POD_DOMAIN="$(printf "$DOMAIN_SCHEMA" "$POD_NAME")"
+fireConsulReloadConfigEvent() {
+	curl -XPUT "http://$CONSUL_HOST:8500/v1/event/fire/reload-config?dc=$CONSUL_DATACENTER" -m 3 -d '' >/dev/null 2>/dev/null \
+		|| (echo "Failed to fire consul reload-config event!" >&2; false)
+}
+
 rm -f "$DEST_FILE" &&
-waitForConsulMaster &&
 mkdir -p "$(dirname "$DEST_FILE")" &&
 jq -n "$(consulConfigJq)" > "$DEST_FILE" &&
+fireConsulReloadConfigEvent &&
 registerHttpHostConsulKvEntries
+
+# TODO: dig @172.16.28.1 consul.service.dc1.consul | grep -E '^[^;]+' | head -1 | grep -Eo '[0-9a-z\.:]+$'
diff --git a/config/opt/bin/launch-pod b/config/opt/bin/launch-pod
--- a/config/opt/bin/launch-pod
+++ b/config/opt/bin/launch-pod
@@ -58,7 +58,9 @@ assertJSON() {
 generateEffectiveJSON() {
 	FIRST_TRANSFORM_JQ="
 		{\"pod\": $1, \"default\": $2} |
-		.effective = ({\"net\": \"default\", \"dns\": \"host\"} + {\"net\": .default.net, \"dns\": .default.dns, \"dns-search\": .default.\"dns-search\"} + .pod) |
+		.effective += {\"net\": \"default\", \"dns\": [\"host\"], \"inject-hosts\": true} |
+		.effective += (.default | with_entries(select(.key == [\"net\", \"dns\", \"dns-search\", \"inject-hosts\"][]))) |
+		.effective += .pod |
 		.effective.services = (.default.services + .pod.services)
 	"
 	EFFECTIVE_JSON="$(jq -n "$FIRST_TRANSFORM_JQ")" &&
@@ -166,27 +168,64 @@ generateEnvVarArgs() {
 	done
 }
 
-runExecBefore() {
+# Args: JQ_QUERY
+generateRunArgs() {
+	# TODO: make calls safe against shell injections
+	GENARGS="$(jq -nr "$POD_JSON | $2" | while read ARGVAL; do
+		GENARGS="$GENARGS $1=$3$ARGVAL" || exit 1
+		echo "$GENARGS"
+	done)" || return 1
+	echo "$GENARGS" | tail -1
+}
+
+runInfrastructureScript() {
+	SCRIPT_TYPE="$1"
 	export POD_NAME
 	export EFFECTIVE_JSON
 	export POD_NET
 	export POD_DNS
+	export POD_IP
 	(POD_NAME_JSON="$(echo "$POD_NAME" | jq -R .)"
 	cd "$POD_DIRECTORY" &&
-	# TODO: remove or make safe: exec-before in pod
-	EXEC_BEFORE="$(echo "$DEFAULTS_JSON" | jq -r "if (.pods.$POD_NAME_JSON | has(\"exec-before\")) then .pods.$POD_NAME_JSON.\"exec-before\"[]? else if (.\"exec-before\") then .\"exec-before\"[]? else \"/bin/true\" end end" | xargs)"
-	sh -c "$EXEC_BEFORE" || (echo "Error in exec-before script: $EXEC_BEFORE" >&2; false) || return 1)
+	# TODO: remove or make call whitespace safe
+	EXEC_SCRIPT="$(jq -nre "$DEFAULTS_JSON | if (.pods.$POD_NAME_JSON | has(\"$SCRIPT_TYPE\")) then .pods.$POD_NAME_JSON.\"$SCRIPT_TYPE\"[]? else if (.\"$SCRIPT_TYPE\") then .\"$SCRIPT_TYPE\"[]? else \"/bin/true\" end end" | xargs)" &&
+	(sh -c "$EXEC_SCRIPT" || (echo "Error in $SCRIPT_TYPE script: $EXEC_SCRIPT" >&2; false))) || return 1
+}
+
+podip() {
+	for SEC in 1 1 3 5; do
+		POD_STATUS="$(rkt status "$POD_UUID")" || return 1
+		if echo "$POD_STATUS" | grep -Eq '^state=running'; then
+			# Print IP
+			echo "$POD_STATUS" | grep -Eo '^networks=[^:]+:[^=]+=[0-9a-z\.:]+' | grep -Eo '[0-9a-z\.:]+$' \
+				|| (echo "Cannot find IP for pod $POD_NAME" >&2; false) || return 1
+			return 0
+		elif echo "$POD_STATUS" | grep -Eq '^state=exited'; then
+			echo 'Pod exited' >&2
+			return 1
+		fi
+		sleep $SEC
+	done
+	echo "Timed out while waiting for pod $POD_NAME" >&2
+	return 1
+}
+
+reload() {
+	trap : 1
+	kill -1 "$POD_PID"
+	trap reload 1
 }
 
 terminateGracefully() {
 	trap : 2 3 9 15
-	kill -15 $POD_PID
-	for SEC in 1 3 7 10; do
-		ps $POD_PID >/dev/null || (echo; false) || exit 0
+	kill -15 "$POD_PID" 2>/dev/null
+	for SEC in 1 1 3 3 5 10; do
+		ps "$POD_PID" >/dev/null || exit "${1:-0}"
 		sleep $SEC
 	done
 	echo "Killing pod since it did not respond: $POD_NAME" >&2
-	kill -9 $POD_PID
+	kill -9 "$POD_PID"
+	exit 1
 }
 
 
@@ -237,31 +276,37 @@ EFFECTIVE_JSON="$(generateEffectiveJSON "$POD_JSON" "$DEFAULTS_JSON")" &&
 POD_JSON="$(jq -n "$EFFECTIVE_JSON | .effective")" &&
 POD_NET="$(jq -nr "$POD_JSON | .net")" &&
 POD_DNS="$(jq -nr "$POD_JSON | .dns")" &&
-POD_DNS_SEARCH="$(jq -n "$POD_JSON | .\"dns-search\" | select(. != null)")" || exit 1
+POD_DNS_SEARCH="$(jq -nr "$POD_JSON | .\"dns-search\" | select(. != null)")" || exit 1
 DNS_SEARCH_OPT=
 [ ! "$POD_DNS_SEARCH" ] || DNS_SEARCH_OPT="--dns-search=$POD_DNS_SEARCH"
 
-runExecBefore "$POD_NAME" || exit 1
+POD_IP=
+runInfrastructureScript on-prepared
 
-# Add host entries
-HOSTS_ENTRY_ARGS=
-HOSTS_ENTRY_ARGS="$(jq -nr "$POD_JSON | .services | keys? | .[]" | while read SERVICE_NAME; do
-	HOSTS_ENTRY_ARGS="$HOSTS_ENTRY_ARGS --hosts-entry=127.0.0.1=$SERVICE_NAME" || exit 1
-	echo "$HOSTS_ENTRY_ARGS"
-done | tail -1)" || exit 1
+RUNARGS="$(generateRunArgs --dns '.dns[]?')" || exit 1
+RUNARGS="$RUNARGS $(generateRunArgs --dns-search '."dns-search"[]?')" || exit 1
+if jq -ne "$POD_JSON | .\"inject-hosts\"" >/dev/null; then
+	RUNARGS="$RUNARGS $(generateRunArgs --hosts-entry '.services | keys? | .[]?' '127.0.0.1=')" || exit 1
+fi
 
 if [ "$VERBOSE" ]; then
 	echo 'Effective configuration:'
 	jq -n "$EFFECTIVE_JSON | .effective"
 	printf 'Will now run rkt commands:\n%s\n' '  rkt prepare --quiet=true'
 	json2rkt "$POD_JSON" | xargs -0n1 | sed -E 's/^/    /g'
-	echo "  rkt run-prepared --hostname=$POD_HOSTNAME --net=$POD_NET --dns=$POD_DNS $DNS_SEARCH_OPT $HOSTS_ENTRY_ARGS CONTAINER_UUID"
+	echo "  rkt run-prepared --hostname=$POD_HOSTNAME --net=$POD_NET $RUNARGS CONTAINER_UUID"
 fi
 
 POD_UUID="$(json2rkt "$POD_JSON" | xargs -0 rkt prepare --quiet=true)" &&
 ([ ! -f "$POD_UUID_FILE" ] || /usr/bin/rkt rm --uuid-file="$POD_UUID_FILE" >/dev/null 2>/dev/null || true) && # Clean up old container
 echo "$POD_UUID" > "$POD_UUID_FILE" || exit 1
-rkt run-prepared --hostname="$POD_HOSTNAME" --net="$POD_NET" --dns="$POD_DNS" $DNS_SEARCH_OPT $HOSTS_ENTRY_ARGS "$POD_UUID" &
+rkt run-prepared --hostname="$POD_HOSTNAME" --net="$POD_NET" $RUNARGS "$POD_UUID" &
 POD_PID=$!
 trap terminateGracefully 2 3 9 15
+trap reload 1
+POD_IP="$(podip)" &&
+runInfrastructureScript on-started || terminateGracefully 1
+unset EFFECTIVE_JSON
+unset DEFAULTS_JSON
+unset POD_JSON
 wait
