container internal health checks propagated to consul TTL health check working

diff --git a/config/opt/bin/configure-consul b/config/opt/bin/configure-consul
--- a/config/opt/bin/configure-consul
+++ b/config/opt/bin/configure-consul
@@ -1,46 +1,52 @@
 #!/bin/sh
 
-[ $# -eq 2 ] && [ "$1" ] && [ "$2" ] || (echo "Usage: $0 CONSULHOST CONFDIR" >&2; false) || exit 1
-[ "$POD_NAME" ] || (echo "Missing env var: POD_NAME" >&2; false) || exit 1
-[ "$EFFECTIVE_JSON" ] || (echo "Missing env var: EFFECTIVE_JSON" >&2; false) || exit 1
-[ "$POD_IP" ] || (echo "Missing env var: POD_IP" >&2; false) || exit 1
+usage() {
+	echo "Usage: $0 {await-consul CONSULHOST}|{register CONSULHOST CONFDIR}|{update CONSULHOST CHECKID CHECKSTATUS CHECKOUTPUT}" >&2
+	exit 1
+}
 
-CONSUL_HOST="$1"
-DEST_FILE="$2/pod-${POD_NAME}.json"
-
-waitForConsulMaster() {
-	for SEC in 1 1 3 3 5 10; do
-		curl -XGET "http://$CONSUL_HOST:8500/v1/kv/?keys" >/dev/null 2>/dev/null && return 0
-		sleep $SEC
+waitForConsul() {
+	for SEC in 1 1 1 1 1 1 1 1 1 1; do
+		curl -XGET "http://$1:8500/v1/kv/?keys" >/dev/null 2>/dev/null && return 0
+		sleep 1
 	done
-	echo "Consul master ($CONSUL_HOST) unavailable" >&2
+	echo "consul ($1) unavailable" >&2
 	return 1
 }
 
-# TODO: Write config into consul master so that no consul client required (Problem: service address must be known)
-consulConfigJq() {
-	POD_NAME_JSON="$(echo "$POD_NAME" | jq -R .)"
-	#"datacenter": $CONSUL_DATACENTER_JSON,
-	#"log_level": "INFO",
-	#"node_name": $POD_NAME_JSON,
-	#"server": false,
-	#.images as \$i | .pod.services | to_entries[] as \$e | \$i[\$e.value.image]?.app?.ports[]? | {
-	#
-	#					"checks": [{
-	#						"script": ("/usr/bin/nc -zvw1" + (if (.protocol == "udp") then "u" else "" end) + " $POD_IP " + (.port|tostring)),
-	#						"interval": "10s"
-	#					}]
-	cat <<-EOF
-		$EFFECTIVE_JSON | {
-			"services": [{
-					"name": $POD_NAME_JSON,
-					"tags": [.pod.services | to_entries[]?.key],
-					"address": "$POD_IP",
-					"enableTagOverride": false
-				}
-			]
-		}
-	EOF
+registerConsulService() {
+	deregisterConsulService "$CONSUL_HOST" "$POD_NAME" &&
+	CONSUL_SERVICE_JSON="$(echo "$EFFECTIVE_JSON" | jq -c \
+		--arg pod_name "$POD_NAME" \
+		--arg pod_ip "$POD_IP" \
+		'{
+				"name": $pod_name,
+				"tags": [.pod.services | to_entries[]?.key],
+				"address": $pod_ip,
+				"enableTagOverride": false,
+				"checks": [[.pod.services | to_entries[] | select(.value.healthcheck != null) | .key] | sort | .[] | {
+					"notes": (. + " app check"),
+					"ttl": "30s"
+				}]
+		}')" &&
+	curl -XPUT "http://$CONSUL_HOST:8500/v1/agent/service/register" -d "$CONSUL_SERVICE_JSON" -m 3
+}
+
+# Args: CONSULHOST PODNAME
+deregisterConsulService() {
+	curl "http://$1:8500/v1/agent/service/deregister/$2"
+}
+
+# Args: APPNAME STATUS STATUSTEXT
+updateConsulServiceCheck() {
+	OUTPUT_JSON="$(echo "$3" | jq -sR .)"
+	CHECKID="$(echo "$EFFECTIVE_JSON" | jq -re --arg pod_name "$POD_NAME" --arg app_name "$1" \
+		'[.pod.services? | to_entries? | .[] | select(.value.healthcheck != null)] |
+		if (length == 1)
+			then ("service:" + $pod_name)
+			else ("service:" + $pod_name + ":" + ([.[].key] | sort | (bsearch($app_name) + 1) | tostring))
+			end')" &&
+	curl -XPUT "http://$CONSUL_HOST:8500/v1/agent/check/update/$CHECKID" -d "{\"status\":\"$2\",\"output\":$OUTPUT_JSON}" -m 3
 }
 
 registerHttpHostConsulKvEntries() {
@@ -81,10 +87,34 @@ fireConsulReloadConfigEvent() {
 		|| (echo "Failed to fire consul reload-config event!" >&2; false)
 }
 
-rm -f "$DEST_FILE" &&
-mkdir -p "$(dirname "$DEST_FILE")" &&
-jq -n "$(consulConfigJq)" > "$DEST_FILE" &&
-fireConsulReloadConfigEvent &&
-registerHttpHostConsulKvEntries
+CONSUL_HOST="$2"
+[ "$2" ] || usage
+[ "$POD_NAME" ] || (echo "Missing env var: POD_NAME" >&2; false) || exit 1
+
+case "$1" in
+	await-consul)
+		waitForConsul "$2"
+	;;
+	register)
+		[ "$EFFECTIVE_JSON" ] || (echo "Missing env var: EFFECTIVE_JSON" >&2; false) || exit 1
+		[ "$POD_IP" ] || (echo "Missing env var: POD_IP" >&2; false) || exit 1
+
+		DEST_FILE="$3/pod-${POD_NAME}.json"
+		registerConsulService &&
+		registerHttpHostConsulKvEntries
+	;;
+	deregister)
+		deregisterConsulService "$CONSUL_HOST" "$POD_NAME" || exit 1
+	;;
+	update)
+		APPNAME="$3"
+		APPSTATUS="$4"
+		APPSTATUSTXT="$5"
+		updateConsulServiceCheck "$APPNAME" "$APPSTATUS" "$APPSTATUSTXT"
+	;;
+	*)
+		usage
+esac
 
 # TODO: dig @172.16.28.1 consul.service.dc1.consul | grep -E '^[^;]+' | head -1 | grep -Eo '[0-9a-z\.:]+$'
+
diff --git a/config/opt/bin/launch-pod b/config/opt/bin/launch-pod
--- a/config/opt/bin/launch-pod
+++ b/config/opt/bin/launch-pod
@@ -23,6 +23,9 @@ validatePodJSON() {
 	assertJSON "$POD_JSON" 0 '.services[]?.environment,.environment | keys? | .[]' '[a-zA-Z0-9_]+' &&
 	assertJSON "$POD_JSON" 1 '.services[]?.image | type' 'string' &&
 	assertJSON "$POD_JSON" 1 '.services[]?.image' '.+/.+' &&
+	assertJSON "$POD_JSON" 0 '.services[]?.healthcheck | select(. != null) | type' 'object' &&
+	assertJSON "$POD_JSON" 0 '.services[]?.healthcheck?.timeout' 'null|[0-9\.]+[dhms]?' &&
+	assertJSON "$POD_JSON" 0 '.services[]?.healthcheck?.interval' 'null|([0-9\.]+[dhms]? ?)' &&
 	assertJSON "$POD_JSON" 0 '.services[]?.http | keys? | .[]' 'port|protect|subdomain' &&
 	assertJSON "$POD_JSON" 0 '.services[]?.http | select(. != null) | .port' '[0-9]+' &&
 	assertJSON "$POD_JSON" 0 '.services[]?.http | select(. != null) | .protect | type' 'boolean|null' &&
@@ -88,7 +91,9 @@ generateEffectiveJSON() {
 		.effective.volumes[]?.source |= (if (startswith("/")) then . else ($pod_dir + "/" + .) end) |
 		.effective.volumes[]?.kind |= (if (. == null) then "host" else . end) |
 		.effective.volumes[]?.readonly |= (if (. == null) then false else . end) |
-		(.effective.services[]?.volumes? | select(. != null)) |= with_entries(.value = if (isfilevol(.value)) then tovolname(.key) else .value end)
+		(.effective.services[]?.volumes? | select(. != null)) |= with_entries(.value = if (isfilevol(.value)) then tovolname(.key) else .value end) |
+		(.effective.services[]?.healthcheck | select(. != null) | .timeout) |= (if (. == null) then "20s" else . end) |
+		(.effective.services[]?.healthcheck | select(. != null) | .interval) |= (if (. == null) then "30s" else . end)
 	' <<-EOF
 		{"pod": $1, "default": $2, "images": $FETCHED_IMAGE_MANIFESTS}
 	EOF
@@ -128,16 +133,67 @@ generateRktRunArgs() {
 	)' | xargs
 }
 
+initHealthChecks() {
+	jq -nre "$DEFAULTS_JSON | if (.pods.$POD_NAME_JSON | has(\"on-checked\")) then .pods.$POD_NAME_JSON else .\"on-checked\" end | select(. != null)" >/dev/null || return 0
+	CHECKS_JSON="$(echo "$POD_JSON" | jq -c '[.services? | to_entries? | .[] | select(.value.healthcheck != null) | {"app": .key, "cmd": .value.healthcheck.cmd, "timeout": .value.healthcheck.timeout, "interval": .value.healthcheck.interval}]')" &&
+	CHECK_COUNT="$(jq -n "$CHECKS_JSON | length")" || return 1
+	CHECK_INDEX=0
+	while [ $CHECK_INDEX -lt $CHECK_COUNT ]; do
+		CHECK_JSON=$CHECK_INDEX
+		CHECK_JSON="$(jq -ne "$CHECKS_JSON | .[$CHECK_INDEX]")" &&
+		CHECK_APP="$(jq -nre "$CHECK_JSON | .app")" &&
+		CHECK_TIMEOUT="$(jq -nre "$CHECK_JSON | .timeout")" &&
+		CHECK_INTERVAL="$(jq -nre "$CHECK_JSON | .interval")" \
+			|| (echo "Invalid/incomplete checkscript: $CHECK_JSON" >&2; false) || return 1
+		runHealthCheck "$CHECK_APP" "$CHECK_JSON" "$CHECK_TIMEOUT"
+		if [ $? -eq 0 ]; then
+			while true; do
+				sleep $CHECK_INTERVAL || exit 1
+				runHealthCheck "$CHECK_APP" "$CHECK_JSON" "$CHECK_TIMEOUT"
+			done &
+			CHECK_PIDS="$! $CHECK_PIDS"
+		else
+			echo "Health check handling for $CHECK_APP failed: $CHECK_JSON" >&2
+		fi
+		CHECK_INDEX="$(expr $CHECK_INDEX + 1)"
+	done
+}
+
+# Args: APP CHECKJSON TIMEOUT
+runHealthCheck() {
+	CHECK_APP="$1"
+	CHECK_JSON="$2"
+	CHECK_TIMEOUT="$3"
+	CHECK_CMD_JSON="$(jq -n "$CHECK_JSON | (.cmd + [\"#\"]) | join(\"\\u0000\")")"
+	CHECK_OUTPUT="$(jq -nr "$CHECK_CMD_JSON" | head -z -n -1 | xargs -0 timeout -s KILL "$CHECK_TIMEOUT" rkt enter --app="$CHECK_APP" "$POD_UUID" 2>&1)"
+	case $? in
+		0)
+			CHECK_STATUS=passing
+		;;
+		1)
+			CHECK_STATUS=warning
+		;;
+		*)
+			CHECK_STATUS=critical
+		;;
+	esac
+	runInfrastructureScript on-checked "$CHECK_APP" "$CHECK_STATUS" "$CHECK_OUTPUT"
+}
+
 runInfrastructureScript() {
 	SCRIPT_TYPE="$1"
+	shift
+	ARGS_JSON='[]'
+	while [ $# -gt 0 ]; do
+		ARGS_JSON="$(echo -n "$1" | jq -sR "$ARGS_JSON + [.]")"
+		shift
+	done
 	export POD_NAME
 	export EFFECTIVE_JSON
 	export POD_IP
-	(POD_NAME_JSON="$(echo "$POD_NAME" | jq -R .)"
-	cd "$POD_DIRECTORY" &&
-	# TODO: remove or make call whitespace safe
-	EXEC_SCRIPT="$(jq -nre "$DEFAULTS_JSON | if (.pods."$POD_NAME" | has(\"$SCRIPT_TYPE\")) then .pods.$POD_NAME_JSON.\"$SCRIPT_TYPE\"[]? else if (.\"$SCRIPT_TYPE\") then .\"$SCRIPT_TYPE\"[]? else \"/bin/true\" end end" | xargs)" &&
-	(sh -c "$EXEC_SCRIPT" || (echo "Error in $SCRIPT_TYPE script: $EXEC_SCRIPT" >&2; false))) || return 1
+	(cd "$POD_DIRECTORY" &&
+	jq -nre "$DEFAULTS_JSON | if (.pods.$POD_NAME_JSON | has(\"$SCRIPT_TYPE\")) then .pods.$POD_NAME_JSON.\"$SCRIPT_TYPE\" else if (.\"$SCRIPT_TYPE\") then .\"$SCRIPT_TYPE\" else [\"/bin/true\"] end end | (. + $ARGS_JSON + [\"#\"]) | join(\"\\u0000\")" |
+	head -z -n -1 | xargs -0 sh || (echo "Error in $SCRIPT_TYPE script" >&2; false)) || return 1
 }
 
 podip() {
@@ -166,6 +222,8 @@ reload() {
 
 terminateGracefully() {
 	trap : 2 3 9 15
+	kill -15 $CHECK_PIDS 2>/dev/null
+	runInfrastructureScript on-terminate
 	kill -15 "$POD_PID" 2>/dev/null
 	for SEC in 1 1 3 3 5 10; do
 		ps "$POD_PID" >/dev/null || exit "${1:-0}"
@@ -204,6 +262,7 @@ shift
 shift
 [ ! -z "$POD_FILE" -a ! -z "$POD_NAME" -a $# -eq 0 ] || usage
 
+POD_NAME_JSON="$(echo "$POD_NAME" | jq -R .)" &&
 DEFAULTS_JSON="$([ ! -f "$DEFAULTS_FILE" ] || cat "$DEFAULTS_FILE")" &&
 DEFAULTS_JSON="${DEFAULTS_JSON:-\{\}}" &&
 POD_DIRECTORY="$(readlink -m "$(dirname "$POD_FILE")")" &&
@@ -236,8 +295,10 @@ POD_PID=$!
 trap terminateGracefully 2 3 9 15
 trap reload 1
 POD_IP="$(podip)" &&
-runInfrastructureScript on-started || terminateGracefully 1
+runInfrastructureScript on-started &&
+sleep 1 &&
+initHealthChecks || terminateGracefully 1
 unset EFFECTIVE_JSON
-unset DEFAULTS_JSON
 unset POD_JSON
 wait
+terminateGracefully
